# Generated by Django 3.0.1 on 2020-01-06 18:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classi', '0001_initial'),
        ('chatmessages', '0002_chatmessagegroup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatMessageGroup',
            new_name='GroupChatMessage',
        ),
    ]
