# Generated by Django 3.0.1 on 2020-01-08 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classi', '0007_auto_20200108_1918'),
        ('accounts', '0003_auto_20200107_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='classe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ProfileClasse', to='classi.Classe', verbose_name='Classe'),
        ),
    ]
