# Generated by Django 3.0.1 on 2020-01-08 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classi', '0007_auto_20200108_1918'),
        ('accounts', '0005_auto_20200108_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='materie_preferite',
        ),
        migrations.AddField(
            model_name='profilepreferenzemateria',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ProfilePreferenzeMateria', to='accounts.Profile', verbose_name='Profile'),
        ),
        migrations.AlterField(
            model_name='profilepreferenzemateria',
            name='materia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='PreferenzaMateria', to='classi.ClasseMateria', verbose_name='Materia'),
        ),
    ]
