# Generated by Django 3.0.1 on 2020-01-09 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classi', '0008_classeturnointerrogazione'),
        ('accounts', '0006_auto_20200108_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileInterrogazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('Confermata', models.BooleanField(default=False, verbose_name='Confermata')),
                ('profile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ProfileInterrogazione', to='accounts.Profile', verbose_name='Profile')),
                ('turnointerrogazione', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ProfileClasseTurnoInterrogazione', to='classi.ClasseTurnoInterrogazione', verbose_name='ProfileClasseTurnoInterrogazione')),
            ],
        ),
    ]
