# Generated by Django 3.0.1 on 2020-01-09 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profileinterrogazione'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileinterrogazione',
            old_name='Confermata',
            new_name='conferma',
        ),
    ]
