# Generated by Django 3.0.1 on 2020-01-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200109_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinterrogazione',
            name='descrizione',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
