# Generated by Django 3.0.1 on 2020-01-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profileinterrogazione_descrizione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinterrogazione',
            name='conferma',
            field=models.IntegerField(default=0),
        ),
    ]
