# Generated by Django 3.0.1 on 2020-01-02 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=200)),
                ('descrizione', models.TextField(default='')),
                ('note', models.TextField(default='')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('anno', models.IntegerField(default=0, verbose_name='Anno della classe')),
                ('sezione', models.CharField(default='', max_length=10)),
                ('creation_progress', models.IntegerField(default=0)),
                ('numero_alunni', models.IntegerField(default=0)),
                ('attiva', models.BooleanField(default=True, verbose_name='Attivo')),
                ('alunni', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Alunni della classe')),
                ('creatore', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='classi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClasseMateria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('description', models.TextField(default='')),
                ('professore', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ClasseOraMateria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ora', models.IntegerField(default=0)),
                ('giorno_della_settimana', models.IntegerField(choices=[(0, 'Lunedì'), (1, 'Martedì'), (2, 'Mercoledì'), (3, 'Giovedì'), (4, 'Venerdì'), (5, 'Sabato'), (6, 'Domenica')], default=0, verbose_name='Giorno della settimana')),
                ('materia', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ClasseOraMateria', to='classi.ClasseMateria', verbose_name='Materie della interrogazione')),
            ],
        ),
        migrations.CreateModel(
            name='ClasseInterrogazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto_string', models.CharField(max_length=200)),
                ('voto', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('descrizione', models.TextField(default='')),
                ('data_interrogazione', models.DateTimeField(default=None)),
                ('alunno_interrogato', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ClasseInterrogazione', to=settings.AUTH_USER_MODEL)),
                ('materia', models.ManyToManyField(blank=True, to='classi.ClasseMateria', verbose_name='Materia della classe')),
            ],
        ),
        migrations.CreateModel(
            name='ClasseImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='rooms/img/%Y/%m/%d')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='classi.Classe')),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='ore_materie',
            field=models.ManyToManyField(blank=True, to='classi.ClasseOraMateria', verbose_name='Alunni della classe'),
        ),
    ]
