# Generated by Django 3.0.1 on 2020-01-07 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classemateria',
            name='professore',
        ),
    ]
