# Generated by Django 3.0.1 on 2020-01-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classi', '0002_remove_classemateria_professore'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='immagine_copertina',
            field=models.ImageField(default=1, upload_to='rooms/img/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classeinterrogazione',
            name='confermato',
            field=models.BooleanField(default=False, verbose_name='Attivo'),
        ),
    ]
