# Generated by Django 3.0.1 on 2020-01-08 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classi', '0004_auto_20200107_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='ore_materie',
        ),
        migrations.AddField(
            model_name='classeoramateria',
            name='classe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ora_classe', to='classi.Classe'),
        ),
        migrations.AlterField(
            model_name='classeoramateria',
            name='materia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ora_materia', to='classi.ClasseMateria', verbose_name='Materie della interrogazione'),
        ),
    ]
