# Generated by Django 3.0.1 on 2020-01-08 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classi', '0005_auto_20200108_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classeoramateria',
            name='materia',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, related_name='ora_materia', to='classi.ClasseMateria', verbose_name='Materie della interrogazione'),
        ),
    ]
