# Generated by Django 3.0.1 on 2020-01-09 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classi', '0007_auto_20200108_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasseTurnoInterrogazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=None)),
                ('classe', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='turno_interrogazione_classe', to='classi.Classe')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turno', to='classi.ClasseMateria', verbose_name='Materie turno interrogazione')),
            ],
        ),
    ]
